// <auto-generated />
using System;
using FakeStoreProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FakeStoreProject.Migrations
{
    [DbContext(typeof(FakeStoreDbContext))]
    [Migration("20220517191203_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FakeStoreProject.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Reykjavik",
                            PostCode = "101",
                            Street = "Store Street"
                        },
                        new
                        {
                            Id = 2,
                            City = "New York",
                            PostCode = "NY505",
                            Street = "Customer Street"
                        },
                        new
                        {
                            Id = 3,
                            City = "Copehagen",
                            PostCode = "CP808",
                            Street = "Danish Streen"
                        });
                });

            modelBuilder.Entity("FakeStoreProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Summer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bedroom"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Living Room"
                        });
                });

            modelBuilder.Entity("FakeStoreProject.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 2,
                            FirstName = "Bob",
                            LastName = "Customer"
                        });
                });

            modelBuilder.Entity("FakeStoreProject.Models.ItemOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ItemsOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("FakeStoreProject.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemOrderId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StoreId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            ItemOrderId = 1,
                            StoreId = 1
                        });
                });

            modelBuilder.Entity("FakeStoreProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListPrice")
                        .HasColumnType("int");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet nisi lacus. Aenean eget felis tempor, blandit velit vel, dictum est. Vestibulum sed diam vulputate, commodo ligula aliquet, dictum mauris. Nullam imperdiet elementum nisi, a venenatis nulla tempus quis. Sed tempor gravida felis. Cras porttitor eleifend auctor. ",
                            ImgUrl = "https://media.istockphoto.com/photos/deck-chair-picture-id918244930",
                            ListPrice = 100,
                            ModelYear = 2000,
                            Name = "Summer Chair",
                            StockId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat.",
                            ImgUrl = "https://media.istockphoto.com/photos/patio-table-set-picture-id903469302",
                            ListPrice = 500,
                            ModelYear = 2004,
                            Name = "Outdoor set",
                            StockId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat. Etiam imperdiet nulla et justo laoreet, nec iaculis purus fringilla. Etiam eget erat vitae ipsum sodales commodo. Praesent at erat maximus, aliquam enim.",
                            ImgUrl = "https://media.istockphoto.com/photos/table-and-chairs-picture-id645618262",
                            ListPrice = 670,
                            ModelYear = 1990,
                            Name = "Table Set",
                            StockId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat. Etiam imperdiet nulla et justo laoreet, nec iaculis purus fringilla. Etiam eget erat vitae ipsum sodales commodo. Praesent at erat maximus, aliquam enim.",
                            ImgUrl = "https://media.istockphoto.com/photos/parasol-picture-id187264061",
                            ListPrice = 400,
                            ModelYear = 1980,
                            Name = "Summer Parasol",
                            StockId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat. Etiam imperdiet nulla et justo laoreet, nec iaculis purus fringilla. Etiam eget erat vitae ipsum sodales commodo. Praesent at erat maximus, aliquam enim",
                            ImgUrl = "https://media.istockphoto.com/photos/gardening-lounge-chair-picture-id182403766",
                            ListPrice = 100,
                            ModelYear = 2000,
                            Name = "Lounge Chair",
                            StockId = 5
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat. Etiam imperdiet nulla et justo laoreet, nec iaculis purus fringilla. Etiam eget erat vitae ipsum sodales commodo. Praesent at erat maximus, aliquam enim ac, tempor ligula. Pellentesque leo enim, ",
                            ImgUrl = "https://media.istockphoto.com/photos/ornamental-plant-with-pink-petunia-flowers-on-a-large-traditional-picture-id1154401941",
                            ListPrice = 250,
                            ModelYear = 2006,
                            Name = "Plant Pot",
                            StockId = 6
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat. Etiam imperdiet nulla et justo laoreet, nec iaculis purus fringilla. Etiam eget erat vitae ipsum sodales commodo. Praesent at erat maximus, aliquam enim ac, tempor ligula. Pellentesque leo enim, ",
                            ImgUrl = "https://media.istockphoto.com/photos/blue-wooden-dresser-isolated-on-white-background-picture-id1162304784",
                            ListPrice = 500,
                            ModelYear = 2018,
                            Name = "Blue Drawer",
                            StockId = 7
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat. Etiam imperdiet nulla et justo laoreet, nec iaculis purus fringilla. Etiam eget erat vitae ipsum sodales commodo. Praesent at erat maximus, aliquam enim ac, tempor ligula. Pellentesque leo enim, ",
                            ImgUrl = "https://media.istockphoto.com/photos/bed-isolated-on-white-3-picture-id173698682",
                            ListPrice = 800,
                            ModelYear = 2010,
                            Name = "Oak Bed",
                            StockId = 8
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat. Etiam imperdiet nulla et justo laoreet, nec iaculis purus fringilla. Etiam eget erat vitae ipsum sodales commodo. Praesent at erat maximus, aliquam enim ac, tempor ligula. Pellentesque leo enim, ",
                            ImgUrl = "https://media.istockphoto.com/photos/brown-vintage-wooden-drawer-isolated-on-white-background-with-path-picture-id947145084",
                            ListPrice = 250,
                            ModelYear = 2000,
                            Name = "Brown Drawer",
                            StockId = 9
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat. Etiam imperdiet nulla et justo laoreet, nec iaculis purus fringilla. Etiam eget erat vitae ipsum sodales commodo. Praesent at erat maximus, aliquam enim ac, tempor ligula. Pellentesque leo enim,",
                            ImgUrl = "https://media.istockphoto.com/photos/sofa-picture-id173240457",
                            ListPrice = 699,
                            ModelYear = 2002,
                            Name = "White Sofa",
                            StockId = 10
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat. Etiam imperdiet nulla et justo laoreet, nec iaculis purus fringilla. Etiam eget erat vitae ipsum sodales commodo. Praesent at erat maximus, aliquam enim ac, tempor ligula. Pellentesque leo enim,",
                            ImgUrl = "https://media.istockphoto.com/photos/white-sofa-with-pillows-picture-id519463114",
                            ListPrice = 799,
                            ModelYear = 1988,
                            Name = "Gray Sofa",
                            StockId = 11
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat. Etiam imperdiet nulla et justo laoreet, nec iaculis purus fringilla. Etiam eget erat vitae ipsum sodales commodo. Praesent at erat maximus, aliquam enim ac, tempor ligula. Pellentesque leo enim,",
                            ImgUrl = "https://media.istockphoto.com/photos/old-retro-sixties-style-chair-in-blue-picture-id933712184",
                            ListPrice = 399,
                            ModelYear = 2000,
                            Name = "Classic Chair",
                            StockId = 12
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat. Etiam imperdiet nulla et justo laoreet, nec iaculis purus fringilla. Etiam eget erat vitae ipsum sodales commodo. Praesent at erat maximus, aliquam enim ac, tempor ligula. Pellentesque leo enim,",
                            ImgUrl = "https://media.istockphoto.com/photos/side-table-picture-id179599149",
                            ListPrice = 200,
                            ModelYear = 2022,
                            Name = "Side Table",
                            StockId = 13
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat. Etiam imperdiet nulla et justo laoreet, nec iaculis purus fringilla. Etiam eget erat vitae ipsum sodales commodo. Praesent at erat maximus, aliquam enim ac, tempor ligula. Pellentesque leo enim,",
                            ImgUrl = "https://media.istockphoto.com/photos/dark-gray-living-rolled-top-club-chair-picture-id939688452",
                            ListPrice = 350,
                            ModelYear = 1989,
                            Name = "Gray Chair",
                            StockId = 14
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent posuere elementum sapien ac suscipit. Integer hendrerit erat sed lorem varius, quis consectetur enim feugiat. Etiam imperdiet nulla et justo laoreet, nec iaculis purus fringilla. Etiam eget erat vitae ipsum sodales commodo. Praesent at erat maximus, aliquam enim ac, tempor ligula. Pellentesque leo enim,",
                            ImgUrl = "https://media.istockphoto.com/photos/sofa-picture-id642715652",
                            ListPrice = 599,
                            ModelYear = 2015,
                            Name = "Small Sofa",
                            StockId = 15
                        });
                });

            modelBuilder.Entity("FakeStoreProject.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("StoreId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Bob",
                            LastName = "Staffmann",
                            ManagerId = 0,
                            StoreId = 1
                        });
                });

            modelBuilder.Entity("FakeStoreProject.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductsId = 1,
                            Quantity = 10,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductsId = 2,
                            Quantity = 13,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 3,
                            ProductsId = 3,
                            Quantity = 0,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 4,
                            ProductsId = 4,
                            Quantity = 50,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 5,
                            ProductsId = 5,
                            Quantity = 22,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 6,
                            ProductsId = 6,
                            Quantity = 4,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 7,
                            ProductsId = 7,
                            Quantity = 3,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 8,
                            ProductsId = 8,
                            Quantity = 10,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 9,
                            ProductsId = 9,
                            Quantity = 15,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 10,
                            ProductsId = 11,
                            Quantity = 25,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 11,
                            ProductsId = 12,
                            Quantity = 60,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 12,
                            ProductsId = 13,
                            Quantity = 1,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 13,
                            ProductsId = 14,
                            Quantity = 7,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 14,
                            ProductsId = 15,
                            Quantity = 9,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 15,
                            ProductsId = 16,
                            Quantity = 18,
                            StoreId = 1
                        });
                });

            modelBuilder.Entity("FakeStoreProject.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Email = "Fakestore@fakestore.com",
                            Name = "FakeStore",
                            Phone = "444-5555"
                        });
                });

            modelBuilder.Entity("FakeStoreProject.Models.ItemOrder", b =>
                {
                    b.HasOne("FakeStoreProject.Models.Product", null)
                        .WithMany("ItemOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FakeStoreProject.Models.Order", b =>
                {
                    b.HasOne("FakeStoreProject.Models.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.HasOne("FakeStoreProject.Models.Store", null)
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FakeStoreProject.Models.Product", b =>
                {
                    b.HasOne("FakeStoreProject.Models.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FakeStoreProject.Models.Staff", b =>
                {
                    b.HasOne("FakeStoreProject.Models.Staff", null)
                        .WithMany("Staffs")
                        .HasForeignKey("StaffId");

                    b.HasOne("FakeStoreProject.Models.Store", null)
                        .WithMany("Staffs")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FakeStoreProject.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FakeStoreProject.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FakeStoreProject.Models.Product", b =>
                {
                    b.Navigation("ItemOrders");
                });

            modelBuilder.Entity("FakeStoreProject.Models.Staff", b =>
                {
                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("FakeStoreProject.Models.Store", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
